spring.application.name=phonepe-wallet
spring.datasource.url=jdbc:mysql://localhost:3380/phonepe_wallet
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true